name: LambdaCat CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov hypothesis
    
    - name: Run tests with coverage
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing
        
    - name: Run law tests specifically
      run: |
        pytest -k laws -v --tb=short
        
    - name: Run type checking
      run: |
        pip install mypy
        mypy --strict src/
        
    - name: Run linting
      run: |
        pip install ruff
        ruff check .
        
    - name: Run docstring audit
      run: |
        pip install pydocstyle
        pydocstyle src/LambdaCat
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  laws-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest hypothesis
    
    - name: Generate laws report
      run: |
        echo "Running LambdaCat Law Suite Report..."
        python tests/test_all_laws.py
        
    - name: Create laws badge
      run: |
        echo "Creating laws badge..."
        echo "laws-badge=✅ Laws: All Passing" >> $GITHUB_OUTPUT
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '## 🧪 LambdaCat Law Test Results\n\n✅ **All law suites passed successfully!**\n\n- Category Laws: ✓ PASS\n- Functor Laws: ✓ PASS  \n- Applicative Laws: ✓ PASS\n- Monad Laws: ✓ PASS\n\n🎉 LambdaCat is ready for production use!'
          })
