name: release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install Poetry
        run: pipx install poetry
      - name: Install deps
        run: poetry install --with dev
      - name: Lint & typecheck
        run: |
          poetry run ruff check src
          poetry run mypy src
      - name: Test
        run: poetry run pytest -q
      - name: Build dists
        run: poetry build
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish

